project/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup/',views.signup,name='signup'),
    path('profile/',views.profile,name='profile'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),

]

project/post/urls.py
from django.urls import path
from . import views

app_name = 'post'
urlpatterns = [

    # Function Based View
    path('all_posts/', views.all_posts, name='all_posts'),
    path('post/<int:id>/', views.one_post, name='post'),
    path('create_post/', views.create_post, name='create_post'),
    path('<int:id>/edit/', views.edit_post, name='edit_post'),

    # Class Based View
    path('all_posts1/',views.PostList.as_view(),name='all_posts1'),
    path('all_posts1/<int:id>/',views.PostDetail.as_view(),name='all_posts1_detail'),
    path('post_create/', views.PostCreate.as_view(), name='post_create'),
    path('post_update/<int:id>/', views.PostUpdate.as_view(), name='post_update'),

]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/',include('django.contrib.auth.urls')),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('admin/', admin.site.urls),
    path('blog/', include('post.urls', namespace='blog')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]
if settings.DEBUG is True:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save


class Profile(models.Model):
    objects = None
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='profile', null=True, blank=True)
    number_phone = models.CharField(max_length=15)
    city = models.ForeignKey('City', related_name='city_user', on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return '%s ' % self.user


def create_profile(sender, **kwargs):
    if kwargs['created']:
        Profile.objects.create(user=kwargs['instance'])


post_save.connect(create_profile,sender=User)


class City(models.Model):
    objects = None
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

project/accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import Profile


class SignUpForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'first_name', 'last_name']


class UserProfile(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['image', 'number_phone', 'city']

project/accounts/views.py
from django.shortcuts import render, redirect
from .forms import SignUpForm, UserProfile, UserForm
from django.urls import reverse
from django.contrib.auth import authenticate, login as auth_login
from .models import Profile


def signup(request):
    form = SignUpForm()
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data['username']
            password = form.cleaned_data['password1']
            user = authenticate(username=username, password=password)
            auth_login(request, user)
            return redirect('accounts:profile')
        else:
            form = SignUpForm()
    return render(request, 'registration/signup.html', {'form': form})


def profile(request):
    my_profile = Profile.objects.get(user=request.user)
    return render(request, 'accounts/profile.html', {'my_profile': my_profile})


def edit_profile(request):
    my_profile = Profile.objects.get(user=request.user)
    user_form = UserForm(instance=request.user)
    user_profile = UserProfile(instance=my_profile)
    if request.method == 'POST':
        user_form = UserForm(request.POST, instance=request.user)
        user_profile = UserProfile(request.POST, request.FILES, instance=my_profile)
        if user_form.is_valid() and user_profile.is_valid():
            user_form.save()
            user_profile1 = user_profile.save(commit=False)
            user_profile1.user = request.user
            user_profile1.save()
            return redirect(reverse('accounts:profile'))
        else:
            user_form = UserForm(request.POST, instance=request.user)
            user_profile = UserProfile(request.POST,instance=my_profile)
    return render(request,'accounts/edit_profile.html',{'user_form':user_form,'user_profile':user_profile})

project/accounts/templates/accounts/edit_profile.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block body %}

<div class="container">
 <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-10 mx-auto">
                    <div class="apply_job_form white-bg">
                        <h4> Edit Profile </h4>
                        <form method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% bootstrap_form user_form %}
                            {% bootstrap_form user_profile %}
                            <button class="btn btn-primary" style="width:100%;" type="submit"> Save Changes </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

project/accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% load static %}

{% load bootstrap4 %}

{% block body %}

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-8" style="margin-left:250px; margin-top:40px;">
                    <div class="job_sumary">
                        <div class="summery_header">
                            <h3> Profile personal page </h3>
                             {% if my_profile.image %}
                                     <img src="{{my_profile.image.url}}" style="margin-left:340px; margin-top:-60px;" width="110" height="110" alt="profile image">
                             {% else %}
                                    <img src="{% static 'img/user/user.png' %}" style="margin-left:340px; margin-top:-60px;" width="110" height="110" alt="profile image">
                             {% endif %}
                        </div>
                        <div class="job_content">
                            <ul>
                                <li> Name : <span>{{my_profile}}</span></li>
                                <li> E-Mail : <span>{{my_profile.user.email}}</span></li>
                                <li> City : <span>{{my_profile.city}}</span></li>
                                <li> Phone-Number : <span> {{my_profile.number_phone}} </span></li>
                            </ul>
                            <br>
                             <p><a href="{% url 'accounts:edit_profile' %}"  class='btn btn-secondary' style="width:100%;"> Edit Profile</a></p>
                        </div>
                    </div>

                </div>
            </div>
        </div>
</div>
{% endblock %}