project/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('signup/',views.signup,name='signup'),
    path('profile/',views.profile,name='profile'),
    path('profile/edit/', views.edit_profile, name='edit_profile'),

]

project/post/urls.py
from django.urls import path
from . import views

app_name = 'post'
urlpatterns = [

    # Function Based View
    path('all_posts/', views.all_posts, name='all_posts'),
    path('post/<int:id>/', views.one_post, name='post'),
    path('create_post/', views.create_post, name='create_post'),
    path('<int:id>/edit/', views.edit_post, name='edit_post'),

    # Class Based View
    path('all_posts1/',views.PostList.as_view(),name='all_posts1'),
    path('all_posts1/<int:id>/',views.PostDetail.as_view(),name='all_posts1_detail'),
    path('post_create/', views.PostCreate.as_view(), name='post_create'),
    path('post_update/<int:id>/', views.PostUpdate.as_view(), name='post_update'),

]

project/project/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('accounts/',include('django.contrib.auth.urls')),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('admin/', admin.site.urls),
    path('blog/', include('post.urls', namespace='blog')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]
if settings.DEBUG is True:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/post/models.py
from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField


class Post(models.Model):
    objects = None
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    content = RichTextField()
    img = models.ImageField(upload_to='media/')
    created_at = models.DateTimeField(auto_now=True)
    created_by = models.ForeignKey(User,related_name='+',on_delete=models.CASCADE)
    active = models.BooleanField(default=True)

    def __str__(self):
        return self.title

project/post/forms.py
from django import forms
from .models import Post
from ckeditor.widgets import CKEditorWidget


class PostForm(forms.ModelForm):
    content = forms.CharField(widget=CKEditorWidget)

    class Meta:
        model = Post
        fields = ['title', 'content', 'img']

project/post/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import Http404
from .models import Post
from .forms import PostForm
from django.contrib import messages
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from .filters import PostFilter
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView


# Start Of Class Based view
class PostList(ListView):
    model = Post  # in template context is : [object_list or post_list]
    context_object_name = 'all_post'
    queryset = Post.objects.filter(active=True)
    template_name = 'post_list.html'
    paginate_by = 3

    def paginate_queryset(self, queryset, page_size):
        try:
            return super(PostList, self).paginate_queryset(queryset, page_size)
        except Http404:
            self.kwargs['page'] = 1
            return super(PostList, self).paginate_queryset(queryset, page_size)

    def get_queryset(self):
        queryset = Post.objects.filter(active=True)
        my_filter = PostFilter(self.request.GET, queryset)
        queryset = my_filter.qs
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['myname'] = 'MuuHamed14'
        return context


class PostDetail(DetailView):
    model = Post
    template_name = 'post_detail.html'
    context_object_name = 'post'
    pk_url_kwarg = 'id'


class PostCreate(CreateView):
    model = Post
    template_name = 'post_create.html'
    fields = ['title', 'content', 'img']

    def form_valid(self, form):
        new_form = form.save(commit=False)
        new_form.user = self.request.user
        form.save()
        return redirect('blog:all_posts1')


class PostUpdate(UpdateView):
    model = Post
    template_name = 'post_update.html'
    fields = ['title', 'content', 'img']
    pk_url_kwarg = 'id'

    def form_valid(self, form):
        new_form = form.save(commit=False)
        new_form.user = self.request.user
        form.save()
        return redirect('blog:all_posts1')


# End Of Class Based view

# Start Of functional Based View
def all_posts(request):
    all_post = Post.objects.filter(active=True)
    my_filter = PostFilter(request.GET, queryset=all_post)
    all_post = my_filter.qs
    paginator = Paginator(all_post, 3)
    page = request.GET.get('page')
    try:
        all_post = paginator.page(page)
    except PageNotAnInteger:
        all_post = paginator.page(1)
    except EmptyPage:
        all_post = paginator.page(paginator.num_pages)
    return render(request, 'all_posts.html', {'all_post': all_post, 'my_filter': my_filter})


def one_post(request, id):
    post = get_object_or_404(Post, id=id)
    return render(request, 'detail.html', {'post': post})


def create_post(request):
    form = PostForm()
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            form1 = form.save(commit=False)
            form1.user = request.user
            form1.created_by = request.user
            form1.save()
            messages.success(request, 'Post Created Successfully')
            return redirect('blog:all_posts')
        else:
            form = PostForm()
    return render(request, 'create_post.html', {'form': form})


def edit_post(request, id):
    post = get_object_or_404(Post, id=id)
    form = PostForm(instance=post)
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            form1 = form.save(commit=False)
            form1.user = request.user
            form1.save()
            messages.success(request, 'Post Edited Successfully')
            return redirect('blog:all_posts')
        else:
            form = PostForm(instance=post)
    return render(request, 'edit_post.html', {'form': form})
# End Of functional Based View

project/post/templates/all_posts.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block head %}

     <form method="GET" class="form-inline my-2 my-lg-0" style="margin-left:755px;">
        {% bootstrap_form my_filter.form %}
        <button class="btn btn-outline-success my-2 my-sm-0" type="submit" style="margin-left:6px;"> Search </button>
    </form>

{% endblock %}

{% block user %}
    {% if user.is_authenticated %}
        <div class="phone_num d-none d-xl-block">
            <a  class="btn btn-primary" style="margin-left:-510px; margin-top:2px; width:100px" href="{% url 'accounts:profile' %}"> My Profile </a>
        </div>


        <div class="phone_num d-none d-xl-block">
            <a  class="btn btn-danger" style="margin-left:-406px; margin-top:2px; width:100px"  href="{% url 'logout' %}"> Log Out</a>
        </div>
    {% else %}
        <div class="phone_num d-none d-xl-block">
            <a  class="btn btn-primary" style="margin-left:-406px; margin-top:2px; width:100px"  href="{% url 'login' %}">Log in</a>
        </div>
    {% endif %}
{% endblock %}

{% block body %}

<div class="jumbotron" style="width:100%">
    <a class="btn btn-primary btn-lg" style="margin-left:440px;" href="{% url 'blog:create_post'%}" role="button"> Add New Post </a>
</div>
        {% for post in all_post %}
        <div class="col-md-4">
            <div class="card" >
                {% if post.img %}
                  <img src="{{post.img.url}}" class="card-img-top" alt="..." >
                {% endif %}
                  <div class="card-body">
                    <h5 class="card-title">{{post}}</h5>
                    <p class="card-text">{{post.content|safe|truncatewords:50}}</p>
                    <a href="{% url 'blog:post' post.id %}" class="btn btn-primary"> Know More </a>
                  </div>
            </div>
        </div>
       {% endfor %}
<div class="container">
    <div aria-label="blog-pagination" style="margin-left:400px; margin-top:50px;">
    <ul class="pagination">
        <!-- Previous -->
        {% if all_post.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{all_post.previous_page_number}}"> Previous </a>
            </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link"> Previous </a>
        </li>
        {% endif %}
       <!-- End Of Previous -->

        <!-- Start Of Loop -->
            {% for post_num in all_post.paginator.page_range %}
                {% if all_post_num == post_num %}
                    <li class="page-item active">
                        {{post_num}}
                            <span class="sr-only">(current)</span>
                    </li>
                {% else %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{post_num}}"> {{post_num}} </a>
                    </li>
                {% endif %}
            {% endfor %}
        <!-- End Of Loop -->


        <!--- Next -->
        {% if all_post.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{all_post.next_page_number}}"> Next </a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <a class="page-link"> Next </a>
            </li>
        {% endif %}
    </ul>
</div>
</div>
{% endblock %}

project/post/templates/create_post.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block body %}

<div style="width:100%">
    <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.media}}
    {% bootstrap_form form %}
    <input type="submit" class="btn btn-success" style="width:100%" value="Save Post">
</form>

</div>
{% endblock %}

project/post/templates/detail.html
{% extends 'base.html' %}


{% block body %}

{% if post.created_by == request.user %}
<div class="jumbotron" style="width:100%">
    <a class="btn btn-primary btn-lg" style="margin-left:440px;" href="{% url 'blog:edit_post' post.id %}" role="button"> Edit Post </a>
</div>
{% else %}

{% endif %}

            <div class="card" style="width:100%;" >
                  {% if post.img %}
                  <img src="{{post.img.url}}" class="card-img-top" alt="...">
                  {% endif %}
                  <div class="card-body">
                    <h5 class="card-title"> {{post}} </h5>
                    <p class="card-text"> {{post.content|safe}} </p>

                  </div>
            </div>
{% endblock %}

project/post/templates/edit_post.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block body %}

<div style="width:100%">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.media}}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-success" style="width:100%" value="Save Changes">
    </form>
</div>

{% endblock %}

project/post/templates/post_create.html
{% extends 'base_generic.html' %}

{% load bootstrap4 %}

{% block content %}

<div style="width:100%">
    <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.media}}
    {% bootstrap_form form %}
    <input type="submit" class="btn btn-success" style="width:100%" value="Save Post">
</form>

</div>
{% endblock %}

project/post/templates/post_detail.html
{% extends 'base.html' %}


{% block body %}

{% if post.created_by == request.user %}
<div class="jumbotron" style="width:100%">
    <a class="btn btn-primary btn-lg" style="margin-left:440px;" href="{% url 'blog:post_update' post.id %}" role="button"> Edit Post </a>
</div>
{% else %}

{% endif %}

            <div class="card" style="width:100%;" >
                  {% if post.img %}
                  <img src="{{post.img.url}}" class="card-img-top" alt="...">
                  {% endif %}
                  <div class="card-body">
                    <h5 class="card-title"> {{post}} </h5>
                    <p class="card-text"> {{post.content|safe}} </p>

                  </div>
            </div>
{% endblock %}

project/post/templates/post_list.html
{% extends 'base.html' %}

{% block user %}
    {% if user.is_authenticated %}
        <div class="phone_num d-none d-xl-block">
            <a  class="btn btn-primary" style="margin-left:-510px; margin-top:2px; width:100px" href="{% url 'accounts:profile' %}"> My Profile </a>
        </div>


        <div class="phone_num d-none d-xl-block">
            <a  class="btn btn-danger" style="margin-left:-406px; margin-top:2px; width:100px"  href="{% url 'logout' %}"> Log Out</a>
        </div>
    {% else %}
        <div class="phone_num d-none d-xl-block">
            <a  class="btn btn-primary" style="margin-left:-406px; margin-top:2px; width:100px"  href="{% url 'login' %}">Log in</a>
        </div>
    {% endif %}
{% endblock %}

{% block body %}

<div class="jumbotron" style="width:100%">
    <a class="btn btn-primary btn-lg" style="margin-left:440px;" href="{% url 'blog:post_create'%}" role="button"> Add New Post </a>
</div>
        {% for post in all_post %}
        <div class="col-md-4">
            <div class="card" >
                {% if post.img %}
                  <img src="{{post.img.url}}" class="card-img-top" alt="..." >
                {% endif %}
                  <div class="card-body">
                    <h5 class="card-title">{{post}}</h5>
                    <p class="card-text">{{post.content|safe|truncatewords:50}}</p>
                    <a href="{% url 'blog:all_posts1_detail' post.id %}" class="btn btn-primary"> Know More </a>
                  </div>
            </div>
        </div>
       {% endfor %}
<div class="container">
    <div aria-label="blog-pagination" style="margin-left:400px; margin-top:50px;">
    <ul class="pagination">
        <!-- Previous -->
        {% if page_obj.has_previous %}
            <li class="page-item">
                <a class="page-link" href="?page={{page_obj.previous_page_number}}"> Previous </a>
            </li>
        {% else %}
        <li class="page-item disabled">
            <a class="page-link"> Previous </a>
        </li>
        {% endif %}
       <!-- End Of Previous -->

        <!-- Start Of Loop -->
            {% for post_num in page_obj.paginator.page_range %}
                {% if page_obj_num == post_num %}
                    <li class="page-item active">
                        {{post_num}}
                            <span class="sr-only">(current)</span>
                    </li>
                {% else %}
                    <li class="page-item">
                        <a class="page-link" href="?page={{post_num}}"> {{post_num}} </a>
                    </li>
                {% endif %}
            {% endfor %}
        <!-- End Of Loop -->


        <!--- Next -->
        {% if page_obj.has_next %}
            <li class="page-item">
                <a class="page-link" href="?page={{page_obj.next_page_number}}"> Next </a>
            </li>
        {% else %}
            <li class="page-item disabled">
                <a class="page-link"> Next </a>
            </li>
        {% endif %}
    </ul>
</div>
</div>
{% endblock %}

project/post/templates/post_update.html
{% extends 'base.html' %}

{% load bootstrap4 %}

{% block body %}

<div style="width:100%">
    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{form.media}}
        {% bootstrap_form form %}
        <input type="submit" class="btn btn-success" style="width:100%" value="Save Changes">
    </form>
</div>

{% endblock %}